name: tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        env:
          # Make imports and relative paths consistent
          PYTHONPATH: ${{ github.workspace }}
          # Test-time env so nothing external is required
          REPO_DB_PATH: ${{ github.workspace }}/repo.db
          PROJECT_ID: primark
          JIRA_SYNC_ON_PIPELINE: "0"
          TRANSCRIPT_FILE: ""
        run: |
          pytest --cov=. --cov-report=term-missing
