name: tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: "test"        # <- prevents SystemExit on import
      OPENAI_MODEL: "gpt-4o-mini"   # <- harmless; won’t be used by unit tests
      TZ: "Europe/London"
      PYTHONHASHSEED: "0"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # DO NOT: pip install -e .

      - name: Show env
        run: |
          python -V
          pip freeze | head -50

      - name: Run tests
        run: pytest -vv --maxfail=1 --tb=short
